In [1]:
using Oscar

  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.1.1


# Covered schemes and elliptic surfaces in OSCAR

Authors: Simon Brandhorst, Matthias Zach  
Related projects: B1, B5 and A22

Related publications:
- Simon Brandhorst, Matthias Zach, Elliptic Fibrations on Vinberg's Most Algebraic K3 Surface, [arXiv:2311.11766](https://doi.org/10.48550/arXiv.2311.11766)
- Simon Brandhorst, Noam D. Elkies, Equations for a K3 Lehmer map, [Journal of Algebraic Geometry 32 (2023), 641-675](https://doi.org/10.1090/jag/810)

The notebook requires a minimum of 16 GiB RAM.

A K3 surface $Y$ may admit infinitely many distinct elliptic fibrations $\pi\colon Y \to \mathbb{P}^1$. 
Likewise the automorphism group of a K3 surface $Y$ can be infinte.  
This notebook shows how to use Oscar to calculate the automorphism group and the elliptic fibrations on $Y$ up to isomorphisms
explicitly.

The running example is Vinberg's "most algebraic K3 surface" $Y_1$, the unique algebraic K3 surface of Picard number $20$ and discriminant $3$. Then we find all elliptic fibrations on $Y_1$ up to isomorphism. 

In Oscar one can represent a scheme in terms of an affine covering and gluing maps between the affine charts. Correspondingly effective divisors are sheaves of ideals.
This point of view is especially useful to deal with singularities, birational maps and intersection numbers of divisors.  

To construct Vinberg's most algebraic K3 surface, we start by defining an elliptic curve over $\mathbb Q(t)$:

In [2]:
Qt, t = polynomial_ring(QQ, :t);
Qtf = fraction_field(Qt);
E = elliptic_curve(Qtf, [0,0,0,0,t^5*(t-1)^2])

Elliptic curve with equation
y^2 = x^3 + t^7 - 2*t^6 + t^5

From such an *elliptic curve* $E$ we can construct a relatively minimal **elliptic surface** $Y_1$, starting from a *Weierstrass model*:

In [3]:
Y1 = elliptic_surface(E, 2)
S = weierstrass_model(Y1)[1]

Scheme
  over rational field
with default covering
  described by patches
    1: scheme(-(x//z)^3 + (y//z)^2 - t^7 + 2*t^6 - t^5)
    2: scheme((z//x)^3*t^7 - 2*(z//x)^3*t^6 + (z//x)^3*t^5 - (z//x)*(y//x)^2 + 1)
    3: scheme((z//y)^3*t^7 - 2*(z//y)^3*t^6 + (z//y)^3*t^5 - (z//y) + (x//y)^3)
    4: scheme((x//z)^3 - (y//z)^2 + s^7 - 2*s^6 + s^5)
    5: scheme((z//x)^3*s^7 - 2*(z//x)^3*s^6 + (z//x)^3*s^5 - (z//x)*(y//x)^2 + 1)
    6: scheme((z//y)^3*s^7 - 2*(z//y)^3*s^6 + (z//y)^3*s^5 - (z//y) + (x//y)^3)
  in the coordinate(s)
    1: [(x//z), (y//z), t]
    2: [(z//x), (y//x), t]
    3: [(z//y), (x//y), t]
    4: [(x//z), (y//z), s]
    5: [(z//x), (y//x), s]
    6: [(z//y), (x//y), s]

Let us look at the gluing of the two Weierstrass charts coming from the two standard charts of $\mathbb{P}^1$

In [4]:
S[1][1,4]

Gluing
  of scheme(-(x//z)^3 + (y//z)^2 - t^7 + 2*t^6 - t^5)
  and scheme((x//z)^3 - (y//z)^2 + s^7 - 2*s^6 + s^5)
along the open subsets
  [(x//z), (y//z), t]   scheme(-(x//z)^3 + (y//z)^2 - t^7 + 2*t^6 - t^5) \ scheme(t)
  [(x//z), (y//z), s]   scheme((x//z)^3 - (y//z)^2 + s^7 - 2*s^6 + s^5) \ scheme(s)
given by the pullback function
  (x//z) -> (x//z)/t^4
  (y//z) -> (y//z)/t^6
       s -> 1/t

The Weierstrass model of $Y_1$ is singular. In order to obtain $Y_1$ itself as a covered scheme, we have to compute a *relatively minimal model* via a resolution of singularities.

In [5]:
# The following two commands lead to a more verbose output; they can be skipped.
# set_verbose_level(:EllipticSurface, 2)
# set_verbose_level(:MorphismFromRationalFunctions, 5)
set_verbose_level(:K3Auto, 1)

1

In [6]:
piS = weierstrass_contraction(Y1)

Composite morphism of
  Hom: elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5 -> scheme over QQ covered with 44 patches
  Hom: scheme over QQ covered with 44 patches -> scheme over QQ covered with 40 patches
  Hom: scheme over QQ covered with 40 patches -> scheme over QQ covered with 38 patches
  Hom: scheme over QQ covered with 38 patches -> scheme over QQ covered with 36 patches
  Hom: scheme over QQ covered with 36 patches -> scheme over QQ covered with 32 patches
  Hom: scheme over QQ covered with 32 patches -> scheme over QQ covered with 30 patches
  Hom: scheme over QQ covered with 30 patches -> scheme over QQ covered with 28 patches
  Hom: scheme over QQ covered with 28 patches -> scheme over QQ covered with 26 patches
  Hom: scheme over QQ covered with 26 patches -> scheme over QQ covered with 24 patches
  Hom: scheme over QQ covered with 24 patches -> scheme over QQ covered with 22 patches
  Hom: scheme over QQ covered with 22 patches -> scheme over QQ covere

For any elliptically fibered K3 surface so constructed we can ask for the *algebraic lattice*. In general, this is a sublattice of the Neron-Severi group, but for Vinberg's K3 surface it is indeed equal to $\mathrm{NS}(Y_1)$. 

In [7]:
basisNSY1, _, NSY1 = algebraic_lattice(Y1);
basisNSY1

20-element Vector{Any}:
 Fiber over (2, 1)
 section: (0 : 1 : 0)
 component A2_1 of fiber over (1, 1)
 component A2_2 of fiber over (1, 1)
 component E8_1 of fiber over (0, 1)
 component E8_2 of fiber over (0, 1)
 component E8_3 of fiber over (0, 1)
 component E8_4 of fiber over (0, 1)
 component E8_5 of fiber over (0, 1)
 component E8_6 of fiber over (0, 1)
 component E8_7 of fiber over (0, 1)
 component E8_8 of fiber over (0, 1)
 component E8_1 of fiber over (1, 0)
 component E8_2 of fiber over (1, 0)
 component E8_3 of fiber over (1, 0)
 component E8_4 of fiber over (1, 0)
 component E8_5 of fiber over (1, 0)
 component E8_6 of fiber over (1, 0)
 component E8_7 of fiber over (1, 0)
 component E8_8 of fiber over (1, 0)

We see there are two fibers of type $\widetilde{E}_8$ over $(0:1)$ and $(1:0)$ and an $\widetilde{A}_2$ fiber over $(1:1)$.
This in agreement with the orders of vanishing of the discriminant of E and its j-invariant as predicted by Tate's algorithm.

In [8]:
factor(Qt, discriminant(E))

-432 * (t - 1)^4 * t^10

In [9]:
j_invariant(E)

0

### The generators for the algebraic lattice are given as effective Weil divisors on the surface

In [10]:
basisNSY1[2] - 3*basisNSY1[5] + 5*basisNSY1[3]

Weil divisor
  on elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5
with coefficients in integer ring
given as the formal sum of
  -3 * component E8_1 of fiber over (0, 1)
   5 * component A2_1 of fiber over (1, 1)
   1 * section: (0 : 1 : 0)

In [11]:
gram_matrix(ambient_space(NSY1))

[0    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[1   -2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[0    0   -2    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[0    0    1   -2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[0    0    0    0   -2    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[0    0    0    0    1   -2    1    0    0    0    0    0    0    0    0    0    0    0    0    0]
[0    0    0    0    0    1   -2    1    0    0    0    1    0    0    0    0    0    0    0    0]
[0    0    0    0    0    0    1   -2    1    0    0    0    0    0    0    0    0    0    0    0]
[0    0    0    0    0    0    0    1   -2    1    0    0    0    0    0    0    0    0    0    0]
[0    0    0    0    0    0    0    0    1   -2    1    0    0    0    0    0    0    0    0    0]
[0    0   

Here is their **intersection matrix**:

The components of the Weil divisors are represented as a **sheaf of ideals**:

In [12]:
# Time to play with the objects defined above
U = affine_charts(Y1) # a list of affine charts for `Y1`
I = first(components(basisNSY1[5])) # a sheaf of ideals on `Y1`
I(U[5]) # a concrete ideal in the coordinate ring of the 5-th chart representing `I`

Ideal generated by
  t
  (e2//e0)

In [13]:
# Some examples for handling of ideal sheaves
J = pushforward(piS, I)

Sheaf of ideals
  on scheme over QQ covered with 6 patches
    1: [(x//z), (y//z), t]   scheme(-(x//z)^3 + (y//z)^2 - t^7 + 2*t^6 - t^5)
    2: [(z//x), (y//x), t]   scheme((z//x)^3*t^7 - 2*(z//x)^3*t^6 + (z//x)^3*t^5 - (z//x)*(y//x)^2 + 1)
    3: [(z//y), (x//y), t]   scheme((z//y)^3*t^7 - 2*(z//y)^3*t^6 + (z//y)^3*t^5 - (z//y) + (x//y)^3)
    4: [(x//z), (y//z), s]   scheme((x//z)^3 - (y//z)^2 + s^7 - 2*s^6 + s^5)
    5: [(z//x), (y//x), s]   scheme((z//x)^3*s^7 - 2*(z//x)^3*s^6 + (z//x)^3*s^5 - (z//x)*(y//x)^2 + 1)
    6: [(z//y), (x//y), s]   scheme((z//y)^3*s^7 - 2*(z//y)^3*s^6 + (z//y)^3*s^5 - (z//y) + (x//y)^3)
with restrictions
  1: Ideal (t, (y//z), (x//z))
  2: Ideal (1)
  3: Ideal (1)
  4: Ideal (1)
  5: Ideal (1)
  6: Ideal (1)

In [14]:
pb_J = pullback(piS, J);
pb_J(U[5])

Ideal generated by
  t
  (e2//e0)*t^2
  (e1//e0)*t^2

In [15]:
is_subset(pb_J, I)

true

In [16]:
Oscar.maximal_associated_points(pb_J)

8-element Vector{Oscar.AbsIdealSheaf}:
 Prime ideal sheaf on Elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5 extended from Ideal (t, (e2//e0)) on scheme((e1//e0)^3*t^2 - (e2//e0)^2 + t^3 - 2*t^2 + t) \ scheme(t - 1)
 Prime ideal sheaf on Elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5 extended from Ideal ((b2//b0), (i1//i0) - (i2//i0)^2) on scheme((i1//i0)^5*(b2//b0)^9 - 2*(i1//i0)^4*(b2//b0)^6 + (i1//i0)^3*(b2//b0)^3 + (i1//i0) - (i2//i0)^2) \ scheme((i1//i0)*(b2//b0)^3 - 1)
 Prime ideal sheaf on Elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5 extended from Ideal ((i2//i0), (i1//i0) - (i2//i0)^2) on scheme((i1//i0)^5*(b2//b0)^9 - 2*(i1//i0)^4*(b2//b0)^6 + (i1//i0)^3*(b2//b0)^3 + (i1//i0) - (i2//i0)^2) \ scheme((i1//i0)*(b2//b0)^3 - 1)
 Prime ideal sheaf on Elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5 extended from Ideal ((i2//i1), (i0//i1) - (i2//i1)^2) on scheme((i0//i1)^6*(g2//g0)^9 - 2*(i0//i1)^4*(g2//g0

## Finding all elliptic fibrations in the nef cone

A great deal of information about a K3 surface,can be deduced from its various $\mathbb{Z}$-**lattices** (integer cohomology, Neron-Severi, ...) and its Hodge structure. 
For any K3 surface $X$ the **elliptic fibrations** are in one-to-one correspondence with the **extremal rays of the nef-cone**. Let us find these rays.

We start out by constructing an ample class in the lattice `NSY1`.

In [17]:
e = matrix(ZZ,1,20,ones(Int,20)); e[1,1]=51;
ample = e*inv(gram_matrix(NSY1))

[103   51   -1   -1   -46   -91   -135   -110   -84   -57   -29   -68   -46   -91   -135   -110   -84   -57   -29   -68]

We confirm that the class is indeed in the interior of a so called Weyl-chamber, by
checking that it is not contained in any hyperplane orthogonal to a $(−2)$-
class.

In [18]:
minimum(rescale(orthogonal_submodule(NSY1, ample),-1))

4

Automorphisms of $Y_1$ act by pushforward on $\mathrm{NS(Y_1)}$. We let OSCAR compute the image $\mathrm{Aut}(Y_1) \to O(\mathrm{NS}(Y_1))$. 
In general this map has finite kernel. In our case it is injective and the image is an **infinite discrete group** of integer matrices.

In [19]:
# WARNING: This computation is expensive! (~5 minutes)
Xaut, Xchambers, Xrational_curves = K3_surface_automorphism_group(NSY1, ample);

computing an initial Weyl vector 


found a lattice of minimum 2 


found a lattice of minimum 4 


new weyl: [61 30 -11 -21 -46 -91 -135 -110 -84 -57 -29 -68 -46 -91 -135 -110 -84 -57 -29 -68 2 -8 -5 5 -4 3] 


Found a chamber with 71 automorphisms


72 automorphism group generators


1 congruence classes of chambers 


2 orbits of rational curves


The return value `Xchambers` is a list of **polyhedral cones** $C_1, \dots, C_n$ which
are contained in the Nef cone. Let $\mathrm{Aut}(C_i) := \mathrm{Aut}(X)C_i$ be the stabilizer of $C_i$. This stabilizer acts on the points of $C_i$. Let $P_i \subset C_i$ be its fundamental
domain. A fundamental domain of the action of $\mathrm{Aut}(X)$ on the Nef cone is
the union of the $P_i$ . In our case $n = 1$.

In [20]:
C = Xchambers[1]

Chamber  in dimension 20 with 36 walls

The walls $W=r^\perp$ of $C$ with $r^2=-2$ and $r \in \mathrm{NS}(X)$ are classes
of smooth rational curves. The rays $f$ of $C$ with $f^2=0$ give elliptic
fibrations.  We now compute the rays of $C$ modulo the **finite group** $\mathrm{Aut}(C)$.

In [21]:
Xelliptic_classes = [f for f in rays(C) if 0 == f*gram_matrix(NSY1)*transpose(f)];
Xelliptic_classes_orb = orbits(gset(matrix_group(aut(C)),(x,g)->x*matrix(g), Xelliptic_classes));
length(Xelliptic_classes_orb)

6

Thus modulo $\mathrm{Aut}(Y_1/\mathbb{C})$ there are **exactly $6$ elliptic fibrations** on $Y_1/\mathbb{C}$. 

We relate the distinct fibrations by so-called "two neighbor steps".

In [22]:
f1 = identity_matrix(ZZ, 20)[1:1,:]; # the first element of `basisNSY1` is the class of the fiber
f1_2neighbors = [f for f in Xelliptic_classes if 2 == (f1*gram_matrix(NSY1)*transpose(f))[1,1]]

3-element Vector{ZZMatrix}:
 [4   2   -1   -1   -2   -4   -6   -5   -4   -3   -2   -3   -4   -7   -10   -8   -6   -4   -2   -5]
 [4   2   0   0   -4   -7   -10   -8   -6   -4   -2   -5   -4   -7   -10   -8   -6   -4   -2   -5]
 [4   2   -1   -1   -4   -7   -10   -8   -6   -4   -2   -5   -2   -4   -6   -5   -4   -3   -2   -3]

From these elliptic divisors we may then again take the two neighbors.

In [23]:
f2, f3, _ = f1_2neighbors;
f2_2neighbors = [f for f in Xelliptic_classes if 2 == (f2*gram_matrix(NSY1)*transpose(f))[1,1]];
fibers = [f1,f2,f3];
todo = [o for o in Xelliptic_classes_orb if !any(f in o for f in fibers)];
while length(todo) > 0
  o = popfirst!(todo)
  f = findfirst(x-> x in o, f2_2neighbors)
  push!(fibers, f2_2neighbors[f])
end
fibers = [vec(collect(i*basis_matrix(NSY1))) for i in fibers]

6-element Vector{Vector{QQFieldElem}}:
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [4, 2, -1, -1, -2, -4, -6, -5, -4, -3, -2, -3, -4, -7, -10, -8, -6, -4, -2, -5]
 [4, 2, 0, 0, -4, -7, -10, -8, -6, -4, -2, -5, -4, -7, -10, -8, -6, -4, -2, -5]
 [6, 3, -1, -1, -5, -10, -15, -12, -9, -6, -3, -8, -5, -10, -15, -12, -9, -6, -3, -8]
 [6, 3, -1, -2, -4, -8, -12, -10, -8, -6, -3, -6, -4, -8, -12, -10, -8, -6, -3, -6]
 [8, 4, -1, -2, -6, -12, -18, -15, -12, -8, -4, -9, -7, -14, -20, -16, -12, -8, -4, -10]

For all 6 fibrations gathered we compute their **Mordell-Weil rank**, the **torsion** subgroup of the Mordell-Weil-group, and the
**ADE-type** of their **singular fibers**. 

In [24]:
[fibration_type(NSY1, f) for f in fibers]

6-element Vector{Tuple{Int64, FinGenAbGroup, Vector{Tuple{Symbol, Int64}}}}:
 (0, Z/1, [(:A, 2), (:E, 8), (:E, 8)])
 (1, Z/2, [(:D, 10), (:E, 7)])
 (0, Z/2, [(:A, 2), (:D, 16)])
 (1, Z/3, [(:A, 17)])
 (0, Z/3, [(:E, 6), (:E, 6), (:E, 6)])
 (0, Z/4, [(:A, 11), (:D, 7)])

## Realizing elliptic fibrations and their transitions

In what follows we aim to compute different Weierstrass-models of
Vinberg's K3 surface which realize different elliptic fibrations. 
Moreover, we wish to identify their minimal desingularizations by explicit **rational maps**. 

To find the elliptic fibration $\pi_2 \colon Y \to \mathbb{P}^1$,
we compute the **linear system** of the following divisor `f2` corresponding to a fiber of $\pi_2$. 

In [25]:
f2 = fibers[2]  # abstractly in the lattice
sum(ZZ(f2[i])*basisNSY1[i] for i in 1:20)  # as a divisor

Weil divisor
  on elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5
with coefficients in integer ring
given as the formal sum of
   -5 * component E8_8 of fiber over (1, 0)
   -2 * component E8_7 of fiber over (1, 0)
   -5 * component E8_4 of fiber over (0, 1)
   -2 * component E8_7 of fiber over (0, 1)
   -6 * component E8_5 of fiber over (1, 0)
   -1 * component A2_1 of fiber over (1, 1)
   -4 * component E8_2 of fiber over (0, 1)
   -4 * component E8_6 of fiber over (1, 0)
    4 * sheaf of ideals
   -7 * component E8_2 of fiber over (1, 0)
   -3 * component E8_6 of fiber over (0, 1)
   -4 * component E8_1 of fiber over (1, 0)
   -4 * component E8_5 of fiber over (0, 1)
   -8 * component E8_4 of fiber over (1, 0)
   -2 * component E8_1 of fiber over (0, 1)
   -1 * component A2_2 of fiber over (1, 1)
  -10 * component E8_3 of fiber over (1, 0)
   -6 * component E8_3 of fiber over (0, 1)
    2 * section: (0 : 1 : 0)
   -3 * component E8_8 of fiber over (0, 1)

We find a linear equivalence $f_2 \sim V + O + P$ given by fibers and sectins according to a Lemma of Shioda.

In [26]:
decomp = Oscar.horizontal_decomposition(Y1, f2);
decomp[2]

Effective weil divisor
  on elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5
with coefficients in integer ring
given as the formal sum of
  1 * component E8_8 of fiber over (1, 0)
  2 * component E8_0 of fiber over (1, 0)
  2 * component E8_7 of fiber over (1, 0)
  1 * component A2_0 of fiber over (1, 1)
  1 * component E8_0 of fiber over (0, 1)
  2 * component E8_4 of fiber over (1, 0)
  2 * component E8_5 of fiber over (1, 0)
  2 * component E8_6 of fiber over (1, 0)
  2 * component E8_3 of fiber over (1, 0)
  2 * section: (0 : 1 : 0)
  1 * component E8_2 of fiber over (1, 0)

We compute an equation for the genus-$1$-fibration given by the linear system of `f2` and the rational change of coordinates `phi1` associated to it.

In [27]:
g, phi1 = two_neighbor_step(Y1, f2); g

-x^3 - t^3*x^2 + t^3*x + y^2

By coincidence $g$ is in minimal Weierstrass form already. In general $g$ will be of the form $y^2-q(x)$ with $q\in \mathbb{Q}(t)[x]$ of degree $4$. To turn it into an honest elliptic fibration one has to choose a point $P$, move it to infinity and apply Tate's algorithm to produce a globally minimal Weierstrass model. The result is an elliptic surface, together with another rational coordinate transformation `phi2`.

In [28]:
kt2 = base_ring(parent(g)); P = kt2.([0, 1, 0]);
Y2, phi2 = elliptic_surface(g, P; minimize=false); Y2

Elliptic surface
  over rational field
with generic fiber
  -x^3 - t^3*x^2 + t^3*x + y^2

Using `phi1` and `phi2` we can write down the **birational rational map** $\phi\colon Y_2 \dashrightarrow Y_1$. On the Weierstrass models, this map can have an indeterminacy locus. It is a deep theorem that $\phi$ extends to an **isomorphism** $\phi \colon Y_2\to Y_1$.
Computations with such maps are **extraordinarily challenging**. 

In [29]:
U2 = weierstrass_chart_on_minimal_model(Y2); U1 = weierstrass_chart_on_minimal_model(Y1);
imgs = phi2.(phi1.(ambient_coordinates(U1))) # k(Y1) -> k(Y2)
phi_rat = morphism_from_rational_functions(Y2, Y1, U2, U1, imgs)

Morphism from rational functions
  from elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
  to elliptic surface with generic fiber -x^3 + y^2 - t^7 + 2*t^6 - t^5
with representatives
  ((x//z),(y//z),t) -> ((x//z)^2*t - (x//z)*t,(x//z)^2*(y//z) - (x//z)*(y//z),(x//z))

In [30]:
# In order to unlock certain features for this type of map
# we need to manually declare that it is an isomorphism and that we know what we're doing.
set_attribute!(phi_rat, :is_isomorphism=>true);

Now we are in a position to pull back divisors from `Y1` or push them forward from `Y2` along `phi_rat`. This enables us to realize further elliptic fibrations, departing from `Y2`. 

In [31]:
pb_basisNSY1 = [pullback(phi_rat, D) for D in basisNSY1]

20-element Vector{WeilDivisor{EllipticSurface{QQField, AbstractAlgebra.Generic.FracFieldElem{QQPolyRingElem}}, ZZRing, ZZRingElem}}:
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic surface with generic fiber -x^3 - t^3*x^2 + t^3*x + y^2
 Effective Weil divisor on elliptic sur

From our previous computations we already know that the corresponding elliptic fibration $\pi_2$ has a
$D_{10}$ and an $E_7$ fiber, a $2$-torsion section and Mordell-Weil rank
one. To find a section of infinite order, we note that $f_2$ intersects
some fiber components of $\pi_1$ with multiplicity one. Therefore they
are sections of $\pi_2$. We can pull those divisors back to `Y2` to obtain the full Neron-Severi lattice there.

In [32]:
point_candidate_indices = [i for i in 1:20 if is_one((gram_matrix(ambient_space(NSY1))*f2)[i])]

4-element Vector{Int64}:
  3
  4
 11
 13

In [33]:
points_on_E2 = Oscar.point_on_generic_fiber_from_divisor.(pb_basisNSY1[point_candidate_indices])

4-element Vector{EllipticCurvePoint{AbstractAlgebra.Generic.FracFieldElem{QQPolyRingElem}}}:
 Point  (1 : -1 : 1)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x
 Point  (1 : 1 : 1)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x
 Point  (0 : 0 : 1)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x
 Point  (0 : 1 : 0)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x

In [34]:
points_on_E2 = [P for P in points_on_E2 if !isinfinite(2*P)]

2-element Vector{EllipticCurvePoint{AbstractAlgebra.Generic.FracFieldElem{QQPolyRingElem}}}:
 Point  (1 : -1 : 1)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x
 Point  (1 : 1 : 1)  of Elliptic curve with equation
y^2 = x^3 + t^3*x^2 - t^3*x

In [35]:
Oscar.set_mordell_weil_basis!(Y2, [points_on_E2[1]])
basisNSY2, _, NSY2 = algebraic_lattice(Y2)
basisNSY2

20-element Vector{WeilDivisor{EllipticSurface{QQField, AbstractAlgebra.Generic.FracFieldElem{QQPolyRingElem}}, ZZRing, ZZRingElem}}:
 Fiber over (1, 1)
 section: (0 : 1 : 0)
 component E7_1 of fiber over (0, 1)
 component E7_2 of fiber over (0, 1)
 component E7_3 of fiber over (0, 1)
 component E7_4 of fiber over (0, 1)
 component E7_5 of fiber over (0, 1)
 component E7_6 of fiber over (0, 1)
 component E7_7 of fiber over (0, 1)
 component D10_1 of fiber over (1, 0)
 component D10_2 of fiber over (1, 0)
 component D10_3 of fiber over (1, 0)
 component D10_4 of fiber over (1, 0)
 component D10_5 of fiber over (1, 0)
 component D10_6 of fiber over (1, 0)
 component D10_7 of fiber over (1, 0)
 component D10_8 of fiber over (1, 0)
 component D10_9 of fiber over (1, 0)
 component D10_10 of fiber over (1, 0)
 section: (1 : -1 : 1)

We do a quick sanity check that we indeed got the correct lattice.

In [36]:
@assert det(gram_matrix(NSY2)) == det(gram_matrix(NSY1))

The pushforward $\phi_*\colon \mathrm{NS}(Y_2) \to \mathrm{NS}(Y_1)$ is a linear map. It can be computed via a specialized routine.

In [37]:
phi_star = Oscar.pushforward_on_algebraic_lattices(phi_rat)  # This computation takes about 15 minutes

Map
  from quadratic space of dimension 20
  to quadratic space of dimension 20

We pull back the fiber classes from $Y_1$ to $Y_2$. 

In [38]:
fibers_on_Y2 = [f*inv(phi_star.matrix) for f in fibers]

6-element Vector{Vector{QQFieldElem}}:
 [4, 2, 0, 0, 0, 0, 0, 0, 0, -4, -4, -8, -7, -6, -5, -4, -3, -2, -1, 0]
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [5, 2, -2, -3, -4, -3, -2, -1, -2, -4, -5, -8, -7, -6, -5, -4, -3, -2, -1, 0]
 [4, 2, -2, -4, -6, -9//2, -3, -3//2, -7//2, -5//2, -3, -5, -9//2, -4, -7//2, -3, -5//2, -2, -3//2, 0]
 [2, 1, -1, -2, -3, -5//2, -2, -3//2, -3//2, -1//2, 0, -1, -3//2, -2, -5//2, -2, -3//2, -1, -1//2, 1]
 [2, 1, -2, -4, -6, -5, -4, -2, -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

Now we are in a position to compute the remaining $4$ elliptic fibrations starting from $Y_2$ in a similar fashion.

In [39]:
two_neighbor_step(Y1,fibers[3])

(-x^3 + (-t^3 + 2)*x^2 - x + y^2, Map: multivariate polynomial ring -> fraction field -> fraction field)

In [40]:
two_neighbor_step(Y2,fibers_on_Y2[4])

(-1//4*x^4 + 1//2*t^2*x^3 - 1//4*t^4*x^2 - x + y^2, Map: multivariate polynomial ring -> fraction field -> fraction field)

In [41]:
two_neighbor_step(Y2,fibers_on_Y2[5])

((-t^2 - 2*t - 1)*x^3 + y^2 - 1//4*t^4, Map: multivariate polynomial ring -> fraction field -> fraction field)

In [42]:
two_neighbor_step(Y2,fibers_on_Y2[6])

(-1//4*t^4*x^4 + 1//2*t^2*x^3 + (-t^3 - 1//4)*x^2 + t*x + y^2, Map: multivariate polynomial ring -> fraction field -> fraction field)